# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-06-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('stupid_count', models.IntegerField(default=0)),
                ('fat_count', models.IntegerField(default=0)),
                ('dumb', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(editable=False)),
            ],
        ),
    ]
